// WIP

///|
#external
pub type ArrayBuffer

///|
pub impl Js for ArrayBuffer with to_js(self) -> Val {
  self |> js
}

///|
#external
pub type SharedArrayBuffer

///|
#external
pub type DataView

///|
#external
pub type Uint8Array

///|
#external
pub type Uint16Array

///|
#external
pub type Uint32Array

///|
#external
pub type Int8Array

///|
#external
pub type Int16Array

///|
#external
pub type Int32Array

///|
#external
pub type Float32Array

///|
#external
pub type Float64Array
